import Foundation

struct ExitError: Error {}

@main
struct VersionGen {
    static func main() throws {
        guard CommandLine.arguments.count > 1 else {
            fputs("Usage: VersionGen <output-path>\n", stderr)
            throw ExitError()
        }
        let outputPath = CommandLine.arguments[1]

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        process.arguments = ["describe", "--tags", "--always"]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = FileHandle.nullDevice

        try process.run()
        process.waitUntilExit()

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        var version = String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown"

        // Strip leading "v" from tags like "v0.1.0"
        if version.hasPrefix("v") {
            version = String(version.dropFirst())
        }

        let swift = """
        // Auto-generated by VersionPlugin — do not edit
        let kolacheVersion = "\(version)"
        """

        try swift.write(toFile: outputPath, atomically: true, encoding: .utf8)
    }
}
