import Foundation

/// Orchestrates Hummingbird project generation.
/// Delegates to the official Hummingbird template (configure.sh) for file generation,
/// then applies Kolache-specific modifications (e.g., core dependency for multi-target).
public struct HummingbirdTemplate {
    public let targetName: String
    public let projectDir: URL
    public var corePackageName: String? = nil

    public init(targetName: String, projectDir: URL, corePackageName: String? = nil) {
        self.targetName = targetName
        self.projectDir = projectDir
        self.corePackageName = corePackageName
    }

    public func generate() throws {
        try HummingbirdTemplateRunner.run(
            projectDir: projectDir,
            packageName: targetName,
            executableName: targetName
        )

        if let coreName = corePackageName {
            try Self.patchPackageSwift(at: projectDir, corePackageName: coreName)
        }
    }

    // MARK: - Package.swift Patching

    /// Patches a Package.swift generated by configure.sh to add a local core package dependency.
    /// Adds `.package(path: "../CoreName")` to package dependencies and `"CoreName"` to the
    /// executable target's dependencies.
    public static func patchPackageSwift(at projectDir: URL, corePackageName: String) throws {
        let packageURL = projectDir.appendingPathComponent("Package.swift")
        var content = try String(contentsOf: packageURL, encoding: .utf8)

        // Insert local package dependency at the start of the dependencies array
        let packageDep = ".package(path: \"../\(corePackageName)\"),"
        if let range = content.range(of: "dependencies: [", range: content.range(of: "dependencies: [")!) {
            let insertPoint = content.index(range.upperBound, offsetBy: 0)
            content.insert(contentsOf: "\n        \(packageDep)", at: insertPoint)
        }

        // Insert core target dependency at the start of the executable target's dependencies
        let targetDep = "\"\(corePackageName)\","
        if let execRange = content.range(of: ".executableTarget(") {
            let searchStart = execRange.upperBound
            if let depsRange = content.range(of: "dependencies: [", range: searchStart..<content.endIndex) {
                let insertPoint = depsRange.upperBound
                content.insert(contentsOf: "\n                \(targetDep)", at: insertPoint)
            }
        }

        try content.write(to: packageURL, atomically: true, encoding: .utf8)
    }
}
